### ISSUE TITLE
Great article mate , any idea about how can i check this router for Insecure WPA2 PSK Generation?

### ISSUE THREAD

**Issue by minanagehsalalma** [QKaiser/voodoo#1]
it's a ZTE router 

model : ZTE ZXHN H108N

[firmware.zip](https://github.com/QKaiser/voodoo/files/6118226/firmware.zip)

thanks :)

**Comment by qkaiser** [comment]
Given the device, it's probably running Linux. If that's true, then they probably use hostapd to setup the wireless access point. Look for anything that configure hostapd dynamically or write to hostapd configuration files (binaries, shell scripts).

Not all wireless access points are affected though, some of them receive a truly randomized value in the factory and that's it.

Some inspiration from another manufacturer: https://github.com/cdiv1e12/upc_keys.py

I don't have much time right now, but don't hesitate to send me a message with your progress (email or twitter dm) and I can help you investigate.

**Comment by minanagehsalalma** [comment]
@QKaiser thanks for the quick reply but 

> If that's true, then they probably use hostapd to setup the wireless access point. Look for anything that configure hostapd dynamically or write to hostapd configuration files (binaries, shell scripts).

do i need a shell for this or the firmware files will do the job ?

**Comment by qkaiser** [comment]
firmware file should be enough

**Comment by minanagehsalalma** [comment]
@QKaiser i am using ida on the httpd bin file and this what i found with searching "PSK" 
![image](https://user-images.githubusercontent.com/20546638/110964288-b52fbf80-835b-11eb-9e3d-f46cbb41d610.png)

and in the CSPD which is the largest file in the whole thing 
![image](https://user-images.githubusercontent.com/20546638/110965698-1a37e500-835d-11eb-889b-4d527435ebf0.png)
the function called dbdefwlanpsk but the one mentioned there isn't the default .... the default looks like this mostly 3Xg6HuJL 

another function with similar content but with no mention of the real password.
![image](https://user-images.githubusercontent.com/20546638/110965954-6edb6000-835d-11eb-88a7-3e881f18ded4.png)

couldn't find any mention of hostapd nor any password setting in the start up scripts ... i even looked in all the lib files. i can't find the default ssid which is the ISP name :/

i also noticed that the default config file is the same for all the routers ... soo it doesn't come with the password already set i think it gets set after the first boot.

what now ? 😅

**Comment by qkaiser** [comment]
> i can't find the default ssid which is the ISP name

That could mean they don't do PSK derivation from known values but rather write randomized values in NVRAM (fields `IGD.LD1.WLAN{1,2}.PSK1`) at the factory.

The first screenshot looks like a function that sets the PSK when you edit it in the admin panel. It's not clear to me what's happening in the two other ones.

I'd recommend you trace functions that are triggered by a factory reset in binaries, or look at scripts that might get called during factory reset procedure.

**Comment by minanagehsalalma** [comment]
> I'd recommend you trace functions that are triggered by a factory reset in binaries, or look at scripts that might get called during factory reset procedure.

@QKaiser  idk how know exactly to do this :/

**Comment by minanagehsalalma** [comment]
1

**Comment by qkaiser** [comment]
I mean no disrespect but you may be lacking foundational knowledge to look for that kind of stuff. Reverse engineering takes time, it's not like you'll find what you're looking for in a day or two. Even more so when you're not sure that it indeed is there.

Two interesting blog posts on the subject of PSK derivation that might be of interest:

https://deadcode.me/blog/2016/07/01/UPC-UBEE-EVW3226-WPA2-Reversing.html
https://www.mustafadur.com/blog/kablonet/

Other than that try to read as much as possible on firmware reversing, ARM assembly, MIPS assembly, and Linux in general. I don't have the time to give you a detailed list of blogs and presentations, but drop me an email or a DM when you have a clear and specific question.

I'm locking this issue now as this repository is not intended as a support forum for reversers looking into other firmwares. I'll delete it in a day or two.
